import { GetStaticPropsResult, NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import Container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';

import { IGroupsDataDocument, IUserTrainingDocument } from 'types';
import { APP_ROUTS } from 'variables';

import { LayoutMain } from 'components/layout';
import { StartPronounToVerb } from 'components/screens';
import { getUserTrainingsStaticProps, getVerbsGroupsStaticProps } from 'utils/staticProps';

interface IPropsConjugateVerbsPage {
  verbsGroups: IGroupsDataDocument[];
  userTraining?: IUserTrainingDocument;
}

const UserId = 1;
const Language = 'es';

const ConjugateVerbsPage: NextPage<IPropsConjugateVerbsPage> = ({ verbsGroups, userTraining }) => {
  return (
    <LayoutMain userTraining={userTraining}>
      <Head>
        <title>Conjugate Verbs</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Container fluid>
        <Row>
          <Col sm={12}>
            <Link href={APP_ROUTS.ADD_VERB}>Add verb if you do not have any</Link>
          </Col>

          <Col sm={12}>
            <StartPronounToVerb userId={UserId} language={Language} verbsGroups={verbsGroups} />
          </Col>
        </Row>
      </Container>
    </LayoutMain>
  );
};

export async function getStaticProps(): Promise<GetStaticPropsResult<IPropsConjugateVerbsPage>> {
  const verbsGroups = await getVerbsGroupsStaticProps(String(UserId), Language);
  const userTraining = await getUserTrainingsStaticProps(String(UserId), Language);

  return {
    props: {
      verbsGroups,
      userTraining,
    },
  };
}

export default ConjugateVerbsPage;
