import { NextPage } from 'next';
import Head from 'next/head';
import Container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';

import Layout from 'components/layout/Layout';

interface IPropsConjugateRegularVerbsPage {}

const ConjugateRegularVerbsPage: NextPage<IPropsConjugateRegularVerbsPage> = (props) => {
  return (
    <Layout>
      <Head>
        <title>Conjugate Regular Verbs</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Container fluid>
        <Row>
          <Col sm={12}>
            <div>
              <p>Conjugate Regular Verbs</p>
            </div>
          </Col>
        </Row>
      </Container>
    </Layout>
  );
};

export default ConjugateRegularVerbsPage;
