import { GetStaticPropsResult, NextPage } from 'next';
import dynamic from 'next/dynamic';
import Head from 'next/head';
import Link from 'next/link';
import Container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';

import { IBaseApiResponse, IVerbsDataDocument } from 'types';
import { getRequest } from 'utils';
import { HTTP_REQUEST_URL } from 'variables';

import Layout from 'components/layout/Layout';

interface IPropsConjugateVerbsPage {
  verbs: IVerbsDataDocument[];
}

const UserId = 1;
const Language = 'es';

const RegularVerbs = dynamic(() => import('components/exercises/RegularVerbs'), { ssr: false });

const ConjugateVerbsPage: NextPage<IPropsConjugateVerbsPage> = ({ verbs }) => {
  return (
    <Layout>
      <Head>
        <title>Conjugate Verbs</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Container fluid>
        <Row>
          <Col sm={12}>
            <Link href="/spanish/add-verb">Add verb if you do not have any</Link>
          </Col>

          <Col sm={12}>
            <RegularVerbs verbs={verbs} />
          </Col>
        </Row>
      </Container>
    </Layout>
  );
};

export async function getStaticProps(): Promise<GetStaticPropsResult<IPropsConjugateVerbsPage>> {
  const { payload: verbsPayload }: IBaseApiResponse = await getRequest(HTTP_REQUEST_URL.VERBS, {
    language: Language,
    userId: String(UserId),
  });

  return {
    props: {
      verbs: verbsPayload,
    },
  };
}

export default ConjugateVerbsPage;
