import { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import Container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';

import { APP_ROUTS } from 'variables';

import { LayoutMain } from 'components/layout/';

interface IPropsSpanishHomePage {}

const SpanishHomePage: NextPage<IPropsSpanishHomePage> = () => {
  return (
    <LayoutMain>
      <Head>
        <title>Spanish Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Container fluid>
        <Row className="mb-4">
          <Col sm={12}>
            <div>
              <h1>Spanish HomePage</h1>
              <p>Get started</p>
            </div>
          </Col>
        </Row>
        <Row className="mb-4">
          <Col sm={4}>
            <div>
              <Link href={APP_ROUTS.CONJUGATE}>Conjugate Verbs</Link>
            </div>
          </Col>
          <Col sm={4}>
            <div>
              <Link href={APP_ROUTS.ADD_VERB}>Add verb</Link>
            </div>
          </Col>
          <Col sm={4}>
            <div>
              <Link href={APP_ROUTS.ADD_PRONOUNS}>Add Pronouns</Link>
            </div>
          </Col>
        </Row>
        <Row className="mb-4">
          <Col sm={4}>
            <div>
              <Link href={APP_ROUTS.VERBS_GROUPS}>Verbs Groups</Link>
            </div>
          </Col>
          <Col sm={4}>
            <div />
          </Col>
          <Col sm={4}>
            <div />
          </Col>
        </Row>
      </Container>
    </LayoutMain>
  );
};

export default SpanishHomePage;
