import { GetStaticPropsResult, NextPage } from 'next';
import Head from 'next/head';
import Container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';

import { BaseCollectionNames, connectToDatabase, getFindByUserAndLanguage } from 'utils/db';
import { IUserTrainingDocument, ModifiedObjectId } from 'types';

import { LayoutMain } from 'components/layout';

import styles from 'pages/index.module.scss';

interface IPropsHomePage {
  userTraining?: IUserTrainingDocument;
}

const UserId = 1;
const Language = 'es';

const HomePage: NextPage<IPropsHomePage> = ({ userTraining }) => {
  return (
    <LayoutMain userTraining={userTraining}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Container fluid className={styles['home-page-container']}>
        <Row>
          <Col sm={12}>
            <div>
              <h1>Homepage</h1>
              <p>Get started</p>
            </div>
          </Col>
          <Col sm={4}>
            <div>
              <h2>Block 1</h2>
            </div>
          </Col>
          <Col sm={4}>
            <div>
              <h2>Block 2</h2>
            </div>
          </Col>
          <Col sm={4}>
            <div>
              <h2>Block 3</h2>
            </div>
          </Col>
        </Row>
      </Container>
    </LayoutMain>
  );
};

export async function getStaticProps(): Promise<GetStaticPropsResult<IPropsHomePage>> {
  const userId = String(UserId);
  const language = Language;
  const client = await connectToDatabase();
  const db = client.db();

  let userTrainingPayload: IUserTrainingDocument[] = [];

  try {
    const result = await db
      .collection<ModifiedObjectId<IUserTrainingDocument>>(`${BaseCollectionNames.USER_TRAININGS}`)
      .find(getFindByUserAndLanguage(userId, language))
      .toArray();

    userTrainingPayload = result.map((item) => ({
      ...item,
      _id: item._id.toString(),
      lastUpdated: item.lastUpdated.toString(),
      trainings: item.trainings.map((training) => ({
        ...training,
        date: training.date.toString(),
      })),
    }));
  } catch (error) {
    client.close();
  }

  return {
    props: {
      userTraining: userTrainingPayload?.[0],
    },
  };
}
export default HomePage;
