import { NextPage } from 'next';
import Head from 'next/head';
import Container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';

import Layout from 'components/layout/Layout';

import styles from 'pages/index.module.scss';

interface IPropsHomePage {}

const HomePage: NextPage<IPropsHomePage> = (props) => {
  return (
    <Layout>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container fluid className={styles['home-page-container']}>
        <Row>
          <Col sm={12}>
            <div>
              <h1>Homepage</h1>
              <p>Get started</p>
            </div>
          </Col>
          <Col sm={4}>
            <div>
              <h2>Block 1</h2>
            </div>
          </Col>
          <Col sm={4}>
            <div>
              <h2>Block 2</h2>
            </div>
          </Col>
          <Col sm={4}>
            <div>
              <h2>Block 3</h2>
            </div>
          </Col>
        </Row>
      </Container>
    </Layout>
  );
};

export default HomePage;
